/*
 * This file is generated by jOOQ.
 */
package io.typst.chzzk.bridge.sqlite.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Event implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer eventId;
    private final String eventChannelId;
    private final String eventSenderId;
    private final String eventSenderName;
    private final String eventMessage;
    private final Long eventTime;
    private final Integer eventPayAmount;

    public Event(Event value) {
        this.eventId = value.eventId;
        this.eventChannelId = value.eventChannelId;
        this.eventSenderId = value.eventSenderId;
        this.eventSenderName = value.eventSenderName;
        this.eventMessage = value.eventMessage;
        this.eventTime = value.eventTime;
        this.eventPayAmount = value.eventPayAmount;
    }

    public Event(
        Integer eventId,
        String eventChannelId,
        String eventSenderId,
        String eventSenderName,
        String eventMessage,
        Long eventTime,
        Integer eventPayAmount
    ) {
        this.eventId = eventId;
        this.eventChannelId = eventChannelId;
        this.eventSenderId = eventSenderId;
        this.eventSenderName = eventSenderName;
        this.eventMessage = eventMessage;
        this.eventTime = eventTime;
        this.eventPayAmount = eventPayAmount;
    }

    /**
     * Getter for <code>event.event_id</code>.
     */
    public Integer getEventId() {
        return this.eventId;
    }

    /**
     * Getter for <code>event.event_channel_id</code>.
     */
    public String getEventChannelId() {
        return this.eventChannelId;
    }

    /**
     * Getter for <code>event.event_sender_id</code>.
     */
    public String getEventSenderId() {
        return this.eventSenderId;
    }

    /**
     * Getter for <code>event.event_sender_name</code>.
     */
    public String getEventSenderName() {
        return this.eventSenderName;
    }

    /**
     * Getter for <code>event.event_message</code>.
     */
    public String getEventMessage() {
        return this.eventMessage;
    }

    /**
     * Getter for <code>event.event_time</code>.
     */
    public Long getEventTime() {
        return this.eventTime;
    }

    /**
     * Getter for <code>event.event_pay_amount</code>.
     */
    public Integer getEventPayAmount() {
        return this.eventPayAmount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Event other = (Event) obj;
        if (this.eventId == null) {
            if (other.eventId != null)
                return false;
        }
        else if (!this.eventId.equals(other.eventId))
            return false;
        if (this.eventChannelId == null) {
            if (other.eventChannelId != null)
                return false;
        }
        else if (!this.eventChannelId.equals(other.eventChannelId))
            return false;
        if (this.eventSenderId == null) {
            if (other.eventSenderId != null)
                return false;
        }
        else if (!this.eventSenderId.equals(other.eventSenderId))
            return false;
        if (this.eventSenderName == null) {
            if (other.eventSenderName != null)
                return false;
        }
        else if (!this.eventSenderName.equals(other.eventSenderName))
            return false;
        if (this.eventMessage == null) {
            if (other.eventMessage != null)
                return false;
        }
        else if (!this.eventMessage.equals(other.eventMessage))
            return false;
        if (this.eventTime == null) {
            if (other.eventTime != null)
                return false;
        }
        else if (!this.eventTime.equals(other.eventTime))
            return false;
        if (this.eventPayAmount == null) {
            if (other.eventPayAmount != null)
                return false;
        }
        else if (!this.eventPayAmount.equals(other.eventPayAmount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        result = prime * result + ((this.eventChannelId == null) ? 0 : this.eventChannelId.hashCode());
        result = prime * result + ((this.eventSenderId == null) ? 0 : this.eventSenderId.hashCode());
        result = prime * result + ((this.eventSenderName == null) ? 0 : this.eventSenderName.hashCode());
        result = prime * result + ((this.eventMessage == null) ? 0 : this.eventMessage.hashCode());
        result = prime * result + ((this.eventTime == null) ? 0 : this.eventTime.hashCode());
        result = prime * result + ((this.eventPayAmount == null) ? 0 : this.eventPayAmount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Event (");

        sb.append(eventId);
        sb.append(", ").append(eventChannelId);
        sb.append(", ").append(eventSenderId);
        sb.append(", ").append(eventSenderName);
        sb.append(", ").append(eventMessage);
        sb.append(", ").append(eventTime);
        sb.append(", ").append(eventPayAmount);

        sb.append(")");
        return sb.toString();
    }
}
