/*
 * This file is generated by jOOQ.
 */
package io.typst.chzzk.bridge.sqlite.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Token implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String tokenChannelId;
    private final String tokenMcUuid;
    private final String tokenAccessToken;
    private final String tokenRefreshToken;
    private final Long tokenExpireTime;

    public Token(Token value) {
        this.tokenChannelId = value.tokenChannelId;
        this.tokenMcUuid = value.tokenMcUuid;
        this.tokenAccessToken = value.tokenAccessToken;
        this.tokenRefreshToken = value.tokenRefreshToken;
        this.tokenExpireTime = value.tokenExpireTime;
    }

    public Token(
        String tokenChannelId,
        String tokenMcUuid,
        String tokenAccessToken,
        String tokenRefreshToken,
        Long tokenExpireTime
    ) {
        this.tokenChannelId = tokenChannelId;
        this.tokenMcUuid = tokenMcUuid;
        this.tokenAccessToken = tokenAccessToken;
        this.tokenRefreshToken = tokenRefreshToken;
        this.tokenExpireTime = tokenExpireTime;
    }

    /**
     * Getter for <code>token.token_channel_id</code>.
     */
    public String getTokenChannelId() {
        return this.tokenChannelId;
    }

    /**
     * Getter for <code>token.token_mc_uuid</code>.
     */
    public String getTokenMcUuid() {
        return this.tokenMcUuid;
    }

    /**
     * Getter for <code>token.token_access_token</code>.
     */
    public String getTokenAccessToken() {
        return this.tokenAccessToken;
    }

    /**
     * Getter for <code>token.token_refresh_token</code>.
     */
    public String getTokenRefreshToken() {
        return this.tokenRefreshToken;
    }

    /**
     * Getter for <code>token.token_expire_time</code>.
     */
    public Long getTokenExpireTime() {
        return this.tokenExpireTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Token other = (Token) obj;
        if (this.tokenChannelId == null) {
            if (other.tokenChannelId != null)
                return false;
        }
        else if (!this.tokenChannelId.equals(other.tokenChannelId))
            return false;
        if (this.tokenMcUuid == null) {
            if (other.tokenMcUuid != null)
                return false;
        }
        else if (!this.tokenMcUuid.equals(other.tokenMcUuid))
            return false;
        if (this.tokenAccessToken == null) {
            if (other.tokenAccessToken != null)
                return false;
        }
        else if (!this.tokenAccessToken.equals(other.tokenAccessToken))
            return false;
        if (this.tokenRefreshToken == null) {
            if (other.tokenRefreshToken != null)
                return false;
        }
        else if (!this.tokenRefreshToken.equals(other.tokenRefreshToken))
            return false;
        if (this.tokenExpireTime == null) {
            if (other.tokenExpireTime != null)
                return false;
        }
        else if (!this.tokenExpireTime.equals(other.tokenExpireTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.tokenChannelId == null) ? 0 : this.tokenChannelId.hashCode());
        result = prime * result + ((this.tokenMcUuid == null) ? 0 : this.tokenMcUuid.hashCode());
        result = prime * result + ((this.tokenAccessToken == null) ? 0 : this.tokenAccessToken.hashCode());
        result = prime * result + ((this.tokenRefreshToken == null) ? 0 : this.tokenRefreshToken.hashCode());
        result = prime * result + ((this.tokenExpireTime == null) ? 0 : this.tokenExpireTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Token (");

        sb.append(tokenChannelId);
        sb.append(", ").append(tokenMcUuid);
        sb.append(", ").append(tokenAccessToken);
        sb.append(", ").append(tokenRefreshToken);
        sb.append(", ").append(tokenExpireTime);

        sb.append(")");
        return sb.toString();
    }
}
