/*
 * This file is generated by jOOQ.
 */
package io.typst.chzzk.bridge.sqlite.tables.records;


import io.typst.chzzk.bridge.sqlite.tables.Event;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EventRecord extends UpdatableRecordImpl<EventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>event.event_id</code>.
     */
    public EventRecord setEventId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>event.event_id</code>.
     */
    public Integer getEventId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>event.event_channel_id</code>.
     */
    public EventRecord setEventChannelId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>event.event_channel_id</code>.
     */
    public String getEventChannelId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>event.event_sender_id</code>.
     */
    public EventRecord setEventSenderId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>event.event_sender_id</code>.
     */
    public String getEventSenderId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>event.event_sender_name</code>.
     */
    public EventRecord setEventSenderName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>event.event_sender_name</code>.
     */
    public String getEventSenderName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>event.event_message</code>.
     */
    public EventRecord setEventMessage(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>event.event_message</code>.
     */
    public String getEventMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>event.event_time</code>.
     */
    public EventRecord setEventTime(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>event.event_time</code>.
     */
    public Long getEventTime() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>event.event_pay_amount</code>.
     */
    public EventRecord setEventPayAmount(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>event.event_pay_amount</code>.
     */
    public Integer getEventPayAmount() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventRecord
     */
    public EventRecord() {
        super(Event.EVENT);
    }

    /**
     * Create a detached, initialised EventRecord
     */
    public EventRecord(Integer eventId, String eventChannelId, String eventSenderId, String eventSenderName, String eventMessage, Long eventTime, Integer eventPayAmount) {
        super(Event.EVENT);

        setEventId(eventId);
        setEventChannelId(eventChannelId);
        setEventSenderId(eventSenderId);
        setEventSenderName(eventSenderName);
        setEventMessage(eventMessage);
        setEventTime(eventTime);
        setEventPayAmount(eventPayAmount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised EventRecord
     */
    public EventRecord(io.typst.chzzk.bridge.sqlite.tables.pojos.Event value) {
        super(Event.EVENT);

        if (value != null) {
            setEventId(value.getEventId());
            setEventChannelId(value.getEventChannelId());
            setEventSenderId(value.getEventSenderId());
            setEventSenderName(value.getEventSenderName());
            setEventMessage(value.getEventMessage());
            setEventTime(value.getEventTime());
            setEventPayAmount(value.getEventPayAmount());
            resetChangedOnNotNull();
        }
    }
}
