/*
 * This file is generated by jOOQ.
 */
package io.typst.chzzk.bridge.sqlite.tables.records;


import io.typst.chzzk.bridge.sqlite.tables.Token;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TokenRecord extends UpdatableRecordImpl<TokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>token.token_channel_id</code>.
     */
    public TokenRecord setTokenChannelId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>token.token_channel_id</code>.
     */
    public String getTokenChannelId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>token.token_mc_uuid</code>.
     */
    public TokenRecord setTokenMcUuid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>token.token_mc_uuid</code>.
     */
    public String getTokenMcUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>token.token_access_token</code>.
     */
    public TokenRecord setTokenAccessToken(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>token.token_access_token</code>.
     */
    public String getTokenAccessToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>token.token_refresh_token</code>.
     */
    public TokenRecord setTokenRefreshToken(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>token.token_refresh_token</code>.
     */
    public String getTokenRefreshToken() {
        return (String) get(3);
    }

    /**
     * Setter for <code>token.token_expire_time</code>.
     */
    public TokenRecord setTokenExpireTime(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>token.token_expire_time</code>.
     */
    public Long getTokenExpireTime() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>token.token_last_sent_event_id</code>.
     */
    public TokenRecord setTokenLastSentEventId(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>token.token_last_sent_event_id</code>.
     */
    public Integer getTokenLastSentEventId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TokenRecord
     */
    public TokenRecord() {
        super(Token.TOKEN);
    }

    /**
     * Create a detached, initialised TokenRecord
     */
    public TokenRecord(String tokenChannelId, String tokenMcUuid, String tokenAccessToken, String tokenRefreshToken, Long tokenExpireTime, Integer tokenLastSentEventId) {
        super(Token.TOKEN);

        setTokenChannelId(tokenChannelId);
        setTokenMcUuid(tokenMcUuid);
        setTokenAccessToken(tokenAccessToken);
        setTokenRefreshToken(tokenRefreshToken);
        setTokenExpireTime(tokenExpireTime);
        setTokenLastSentEventId(tokenLastSentEventId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TokenRecord
     */
    public TokenRecord(io.typst.chzzk.bridge.sqlite.tables.pojos.Token value) {
        super(Token.TOKEN);

        if (value != null) {
            setTokenChannelId(value.getTokenChannelId());
            setTokenMcUuid(value.getTokenMcUuid());
            setTokenAccessToken(value.getTokenAccessToken());
            setTokenRefreshToken(value.getTokenRefreshToken());
            setTokenExpireTime(value.getTokenExpireTime());
            setTokenLastSentEventId(value.getTokenLastSentEventId());
            resetChangedOnNotNull();
        }
    }
}
