/*
 * This file is generated by jOOQ.
 */
package io.typst.chzzk.bridge.sqlite;


import io.typst.chzzk.bridge.sqlite.tables.Event;
import io.typst.chzzk.bridge.sqlite.tables.Token;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>event</code>.
     */
    public final Event EVENT = Event.EVENT;

    /**
     * The table <code>token</code>.
     */
    public final Token TOKEN = Token.TOKEN;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Event.EVENT,
            Token.TOKEN
        );
    }
}
