/*
 * This file is generated by jOOQ.
 */
package io.typst.chzzk.bridge.sqlite;


import io.typst.chzzk.bridge.sqlite.tables.Token;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_TOKEN_MC_UUID = Internal.createIndex(DSL.name("idx_token_mc_uuid"), Token.TOKEN, new OrderField[] { Token.TOKEN.TOKEN_MC_UUID }, false);
}
