/*
 * This file is generated by jOOQ.
 */
package io.typst.chzzk.bridge.sqlite;


import io.typst.chzzk.bridge.sqlite.tables.Event;
import io.typst.chzzk.bridge.sqlite.tables.Token;
import io.typst.chzzk.bridge.sqlite.tables.records.EventRecord;
import io.typst.chzzk.bridge.sqlite.tables.records.TokenRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EventRecord> EVENT__PK_EVENT = Internal.createUniqueKey(Event.EVENT, DSL.name("pk_event"), new TableField[] { Event.EVENT.EVENT_ID }, true);
    public static final UniqueKey<TokenRecord> TOKEN__PK_TOKEN = Internal.createUniqueKey(Token.TOKEN, DSL.name("pk_token"), new TableField[] { Token.TOKEN.TOKEN_CHANNEL_ID }, true);
    public static final UniqueKey<TokenRecord> TOKEN__UK_TOKEN_1_111080488 = Internal.createUniqueKey(Token.TOKEN, DSL.name("uk_token_1_111080488"), new TableField[] { Token.TOKEN.TOKEN_MC_UUID }, true);
}
