/*
 * This file is generated by jOOQ.
 */
package io.typst.chzzk.bridge.sqlite;


import io.typst.chzzk.bridge.sqlite.tables.Event;
import io.typst.chzzk.bridge.sqlite.tables.Token;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>event</code>.
     */
    public static final Event EVENT = Event.EVENT;

    /**
     * The table <code>token</code>.
     */
    public static final Token TOKEN = Token.TOKEN;
}
