/*
 * This file is generated by jOOQ.
 */
package io.typst.chzzk.bridge.sqlite.tables;


import io.typst.chzzk.bridge.sqlite.DefaultSchema;
import io.typst.chzzk.bridge.sqlite.Keys;
import io.typst.chzzk.bridge.sqlite.tables.records.EventRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Event extends TableImpl<EventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>event</code>
     */
    public static final Event EVENT = new Event();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventRecord> getRecordType() {
        return EventRecord.class;
    }

    /**
     * The column <code>event.event_id</code>.
     */
    public final TableField<EventRecord, Integer> EVENT_ID = createField(DSL.name("event_id"), SQLDataType.INTEGER.identity(true), this, "");

    /**
     * The column <code>event.event_channel_id</code>.
     */
    public final TableField<EventRecord, String> EVENT_CHANNEL_ID = createField(DSL.name("event_channel_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>event.event_sender_id</code>.
     */
    public final TableField<EventRecord, String> EVENT_SENDER_ID = createField(DSL.name("event_sender_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>event.event_sender_name</code>.
     */
    public final TableField<EventRecord, String> EVENT_SENDER_NAME = createField(DSL.name("event_sender_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>event.event_message</code>.
     */
    public final TableField<EventRecord, String> EVENT_MESSAGE = createField(DSL.name("event_message"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>event.event_time</code>.
     */
    public final TableField<EventRecord, Long> EVENT_TIME = createField(DSL.name("event_time"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>event.event_pay_amount</code>.
     */
    public final TableField<EventRecord, Integer> EVENT_PAY_AMOUNT = createField(DSL.name("event_pay_amount"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    private Event(Name alias, Table<EventRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Event(Name alias, Table<EventRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>event</code> table reference
     */
    public Event(String alias) {
        this(DSL.name(alias), EVENT);
    }

    /**
     * Create an aliased <code>event</code> table reference
     */
    public Event(Name alias) {
        this(alias, EVENT);
    }

    /**
     * Create a <code>event</code> table reference
     */
    public Event() {
        this(DSL.name("event"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<EventRecord, Integer> getIdentity() {
        return (Identity<EventRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<EventRecord> getPrimaryKey() {
        return Keys.EVENT__PK_EVENT;
    }

    @Override
    public Event as(String alias) {
        return new Event(DSL.name(alias), this);
    }

    @Override
    public Event as(Name alias) {
        return new Event(alias, this);
    }

    @Override
    public Event as(Table<?> alias) {
        return new Event(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Event rename(String name) {
        return new Event(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Event rename(Name name) {
        return new Event(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Event rename(Table<?> name) {
        return new Event(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Event where(Condition condition) {
        return new Event(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Event where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Event where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Event where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Event where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Event where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Event where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Event where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Event whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Event whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
