/*
 * This file is generated by jOOQ.
 */
package io.typst.chzzk.bridge.sqlite.tables;


import io.typst.chzzk.bridge.sqlite.DefaultSchema;
import io.typst.chzzk.bridge.sqlite.Indexes;
import io.typst.chzzk.bridge.sqlite.Keys;
import io.typst.chzzk.bridge.sqlite.tables.records.TokenRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Token extends TableImpl<TokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>token</code>
     */
    public static final Token TOKEN = new Token();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TokenRecord> getRecordType() {
        return TokenRecord.class;
    }

    /**
     * The column <code>token.token_channel_id</code>.
     */
    public final TableField<TokenRecord, String> TOKEN_CHANNEL_ID = createField(DSL.name("token_channel_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>token.token_mc_uuid</code>.
     */
    public final TableField<TokenRecord, String> TOKEN_MC_UUID = createField(DSL.name("token_mc_uuid"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>token.token_access_token</code>.
     */
    public final TableField<TokenRecord, String> TOKEN_ACCESS_TOKEN = createField(DSL.name("token_access_token"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>token.token_refresh_token</code>.
     */
    public final TableField<TokenRecord, String> TOKEN_REFRESH_TOKEN = createField(DSL.name("token_refresh_token"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>token.token_expire_time</code>.
     */
    public final TableField<TokenRecord, Long> TOKEN_EXPIRE_TIME = createField(DSL.name("token_expire_time"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>token.token_last_sent_event_id</code>.
     */
    public final TableField<TokenRecord, Integer> TOKEN_LAST_SENT_EVENT_ID = createField(DSL.name("token_last_sent_event_id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    private Token(Name alias, Table<TokenRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Token(Name alias, Table<TokenRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>token</code> table reference
     */
    public Token(String alias) {
        this(DSL.name(alias), TOKEN);
    }

    /**
     * Create an aliased <code>token</code> table reference
     */
    public Token(Name alias) {
        this(alias, TOKEN);
    }

    /**
     * Create a <code>token</code> table reference
     */
    public Token() {
        this(DSL.name("token"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_TOKEN_MC_UUID);
    }

    @Override
    public UniqueKey<TokenRecord> getPrimaryKey() {
        return Keys.TOKEN__PK_TOKEN;
    }

    @Override
    public List<UniqueKey<TokenRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TOKEN__UK_TOKEN_1_111080488);
    }

    @Override
    public Token as(String alias) {
        return new Token(DSL.name(alias), this);
    }

    @Override
    public Token as(Name alias) {
        return new Token(alias, this);
    }

    @Override
    public Token as(Table<?> alias) {
        return new Token(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Token rename(String name) {
        return new Token(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Token rename(Name name) {
        return new Token(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Token rename(Table<?> name) {
        return new Token(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Token where(Condition condition) {
        return new Token(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Token where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Token where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Token where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Token where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Token where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Token where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Token where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Token whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Token whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
